# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: 5
#   host: localhost
#   username: postgres
#   password: postgres

# development:
#   <<: *default
#   database: aws_test_development

# test:
#   <<: *default
#   database: aws_test_test_case


production:
  adapter: postgresql
  encoding: unicode
  database: aws_test_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432

# Action Cable production (cable) database
cable:
  adapter: postgresql
  encoding: unicode
  database: aws_test_production
  username: postgres
  password: postgres
  host: localhost

queue:
  adapter: postgresql
  encoding: unicode
  database: aws_test_production
  username: postgres
  password: postgres
  host: localhost


cache:
  adapter: postgresql
  encoding: unicode
  database: aws_test_production
  username: postgres
  password: postgres
  host: localhost
